### ISSUE TITLE
iOS 17.4 无法连接设备。

### ISSUE THREAD

**Issue by Cheney2333** [iOSRealRun/iOSRealRun-cli-17#6]
![image](https://github.com/iOSRealRun/iOSRealRun-cli-17/assets/94615487/d5b3d374-2eee-4b80-bf68-2619211c802a)

**Comment by Geniucker** [comment]
试试看先打开itunes再开realrun

**Comment by Geniucker** [comment]
试试升级pymobiledevice3
```
pip install -U pymobiledevice3
```

**Comment by Geniucker** [comment]
我另一台电脑复现了这个问题，应该是没有安装iTunes，从Microsoft Store里安装iTunes应该就能解决（如果没解决尝试先打开iTunes再运行realrun

**Comment by hanyin111** [comment]
请问你解决了这个问题吗？我也是这样😭

**Comment by Cheney2333** [comment]
没解决，自己跑吧hhh
